/**
 * HLAS-PMS에서 공통으로 사용하는 상수.
 *
 * 신규 기능은 시트명, 상태값, 로그 유형 등의 공통 문자열을
 * 기능 코드에 직접 작성하지 않고 이 객체를 참조한다.
 */
const HLAS_CONSTANTS = Object.freeze({
  SHEETS: Object.freeze({
    PROJECT: '01_PROJECT',
    EPIC: '02_EPIC',
    FEATURE: '03_FEATURE',
    FUNCTION: '04_FUNCTION',
    TASK: '05_TASK',
    USER: '06_USER',
    AUDIT: '07_AUDIT',
    NOTIFICATION: '08_NOTIFICATION',
    BACKUP_HISTORY: '09_BACKUP_HISTORY',
    WORKFLOW_HISTORY: '10_WORKFLOW_HISTORY',
    ANALYTICS_CACHE: '11_ANALYTICS_CACHE',
    API_LOG: '12_API_LOG',
    WEBHOOK: '13_WEBHOOK',
    SYSTEM_HEALTH: '14_SYSTEM_HEALTH',
    RUNTIME_METRICS: '15_RUNTIME_METRICS',
    FEATURE_FLAG: '16_FEATURE_FLAG',
    CHANGELOG: '09_CHANGELOG',
  }),
  ENTITY: Object.freeze({
    PROJECT: 'PROJECT',
    EPIC: 'EPIC',
    FEATURE: 'FEATURE',
    FUNCTION: 'FUNCTION',
    TASK: 'TASK',
    AUDIT: 'AUDIT',
    NOTIFICATION: 'NOTIFICATION',
    BACKUP: 'BACKUP',
    IMPORT: 'IMPORT',
    EXPORT: 'EXPORT',
    WORKFLOW: 'WORKFLOW',
    APPROVAL: 'APPROVAL',
    ANALYTICS: 'ANALYTICS',
    REPORT: 'REPORT',
    API: 'API',
    WEBHOOK: 'WEBHOOK',
    INTEGRATION: 'INTEGRATION',
    PLATFORM: 'PLATFORM',
    FEATURE_FLAG: 'FEATURE_FLAG',
    MAINTENANCE: 'MAINTENANCE',
  }),
  STATUS: Object.freeze({
    IN_PROGRESS: '진행중',
    ON_HOLD: '보류',
    COMPLETED: '완료',
    CANCELLED: '취소',
    VALUES: Object.freeze(['진행중', '보류', '완료', '취소']),
  }),
  PRIORITY: Object.freeze({
    URGENT: '긴급',
    HIGH: '높음',
    NORMAL: '보통',
    LOW: '낮음',
    VALUES: Object.freeze(['긴급', '높음', '보통', '낮음']),
  }),
  LOG_TYPE: Object.freeze({
    PROJECT_CREATE: 'PROJECT 생성',
    PROJECT_DELETE: 'PROJECT 삭제',
    EPIC_CREATE: 'EPIC 생성',
    EPIC_DELETE: 'EPIC 삭제',
    FEATURE_CREATE: 'FEATURE 생성',
    FEATURE_UPDATE: 'FEATURE 수정',
    FEATURE_DELETE: 'FEATURE 삭제',
    FUNCTION_CREATE: 'FUNCTION 생성',
    FUNCTION_UPDATE: 'FUNCTION 수정',
    FUNCTION_DELETE: 'FUNCTION 삭제',
    TASK_CREATE: 'TASK 생성',
    TASK_UPDATE: 'TASK 수정',
    TASK_DELETE: 'TASK 삭제',
  }),
  LOG_RESULT: Object.freeze({
    SUCCESS: '성공',
    FAILURE: '실패',
  }),
  ID: Object.freeze({
    PROJECT_PREFIX: 'PROJ-',
    PROJECT_LEGACY_PREFIX: 'PRJ-',
    EPIC_PREFIX: 'EPIC-',
    FEATURE_PREFIX: 'FEAT-',
    FUNCTION_PREFIX: 'FUNC-',
    TASK_PREFIX: 'TASK-',
    PAD_LENGTH: 4,
  }),
  SEARCH: Object.freeze({
    ASC: 'asc',
    DESC: 'desc',
    SORT_ORDERS: Object.freeze(['asc', 'desc']),
  }),
  ROLE: Object.freeze({
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    USER: 'USER',
    VIEWER: 'VIEWER',
    VALUES: Object.freeze(['ADMIN', 'MANAGER', 'USER', 'VIEWER']),
  }),
  PERMISSION: Object.freeze({
    READ: 'READ',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    DASHBOARD: 'DASHBOARD',
  }),
  AUDIT_ACTION: Object.freeze({
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    LOGIN: 'LOGIN',
    DASHBOARD: 'DASHBOARD',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    ERROR: 'ERROR',
    SCHEDULER: 'SCHEDULER',
    IMPORT: 'IMPORT',
    EXPORT: 'EXPORT',
    BACKUP: 'BACKUP',
    RESTORE: 'RESTORE',
    DELETE_BACKUP: 'DELETE_BACKUP',
    WORKFLOW_CHANGE: 'WORKFLOW_CHANGE',
    APPROVAL: 'APPROVAL',
    REJECT: 'REJECT',
    REPORT: 'REPORT',
    CACHE_CREATE: 'CACHE_CREATE',
    CACHE_DELETE: 'CACHE_DELETE',
    API_CALL: 'API_CALL',
    AUTH_FAILURE: 'AUTH_FAILURE',
    RATE_LIMIT: 'RATE_LIMIT',
    EVENT_PUBLISH: 'EVENT_PUBLISH',
    WEBHOOK_FAILURE: 'WEBHOOK_FAILURE',
    HEALTH_CHECK: 'HEALTH_CHECK',
    RECOVERY: 'RECOVERY',
    CIRCUIT_OPEN: 'CIRCUIT_OPEN',
    FEATURE_FLAG_CHANGE: 'FEATURE_FLAG_CHANGE',
    MAINTENANCE_CHANGE: 'MAINTENANCE_CHANGE',
  }),
  API: Object.freeze({
    VERSION: 'v1', RATE_LIMIT_PER_HOUR: 100, KEY_PREFIX: 'HLAS-',
    ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE',
    ENDPOINTS: Object.freeze(['PROJECT', 'FEATURE', 'FUNCTION', 'TASK', 'USER', 'REPORT']),
    METHODS: Object.freeze(['GET', 'POST', 'PUT', 'DELETE']),
  }),
  INTEGRATION_TYPE: Object.freeze({
    ERP: 'ERP', WMS: 'WMS', MES: 'MES',
    GOOGLE_WORKSPACE: 'GOOGLE_WORKSPACE', GENERIC_REST: 'GENERIC_REST',
  }),
  HEALTH_STATUS: Object.freeze({
    HEALTHY: 'HEALTHY', DEGRADED: 'DEGRADED', DOWN: 'DOWN',
  }),
  CIRCUIT_STATE: Object.freeze({
    CLOSED: 'CLOSED', OPEN: 'OPEN', HALF_OPEN: 'HALF_OPEN',
  }),
  ENVIRONMENT: Object.freeze({
    DEV: 'DEV', TEST: 'TEST', PROD: 'PROD',
    VALUES: Object.freeze(['DEV', 'TEST', 'PROD']),
  }),
  AUDIT_RESULT: Object.freeze({
    SUCCESS: 'SUCCESS',
    FAIL: 'FAIL',
    DENIED: 'DENIED',
  }),
  NOTIFICATION_TYPE: Object.freeze({
    INFO: 'INFO',
    WARNING: 'WARNING',
    ERROR: 'ERROR',
    SUCCESS: 'SUCCESS',
    VALUES: Object.freeze(['INFO', 'WARNING', 'ERROR', 'SUCCESS']),
  }),
  NOTIFICATION_STATUS: Object.freeze({
    UNREAD: 'UNREAD',
    READ: 'READ',
    VALUES: Object.freeze(['UNREAD', 'READ']),
  }),
  NOTIFICATION_CHANNEL: Object.freeze({
    IN_APP: 'IN_APP',
    EMAIL: 'EMAIL',
    GOOGLE_CHAT: 'GOOGLE_CHAT',
    SLACK: 'SLACK',
    VALUES: Object.freeze(['IN_APP', 'EMAIL', 'GOOGLE_CHAT', 'SLACK']),
  }),
  WORKFLOW_STATUS: Object.freeze({
    DRAFT: 'DRAFT',
    READY: 'READY',
    IN_PROGRESS: 'IN_PROGRESS',
    WAITING_APPROVAL: 'WAITING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    VALUES: Object.freeze([
      'DRAFT', 'READY', 'IN_PROGRESS', 'WAITING_APPROVAL',
      'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED',
    ]),
  }),
  USER_STATUS: Object.freeze({
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
  }),
  MASTER_DATA: Object.freeze({
    SCRIPT_PROPERTY_KEY: 'HLAS_MASTER_SPREADSHEET_ID',
    MASTER_SHEET: '기초',
    ORDER_SHEET: '주문내역',
    STORAGE_STATUSES: Object.freeze([
      '상온',
      '냉장(가공)',
      '냉장',
      '냉동',
      '빵',
      '기타',
    ]),
    DEPENDENCIES: Object.freeze([
      '주문내역',
      '주문공급',
      '매장공급',
      '집품',
      '검수',
      '출고',
    ]),
    SEVERITY: Object.freeze({
      ERROR: 'ERROR',
      WARNING: 'WARNING',
      INFO: 'INFO',
    }),
  }),
  ENTITY_TYPE: Object.freeze({
    PRODUCT: 'PRODUCT',
    PRODUCER: 'PRODUCER',
    AGREEMENT: 'AGREEMENT',
    RECEIVING: 'RECEIVING',
    RETURN: 'RETURN',
    ORDER: 'ORDER',
    SHIPMENT: 'SHIPMENT',
    INVENTORY: 'INVENTORY',
    ROUTE: 'ROUTE',
    FUND_RULE: 'FUND_RULE',
    FUND_HISTORY: 'FUND_HISTORY',
  }),
  TABLE_TYPE: Object.freeze({
    MASTER: 'MASTER',
    TRANSACTION: 'TRANSACTION',
    ANALYTICS: 'ANALYTICS',
    RULE: 'RULE',
  }),
  COLUMN_NAME: Object.freeze({
    PRODUCER_ID: '생산자번호',
    PRODUCER_NAME: '생산자명',
    ITEM_CODE: '품번',
    ITEM_NAME: '물품명',
    AGREEMENT_ID: '약정번호',
    RECEIVING_ID: '입고번호',
    RETURN_ID: '반품번호',
    ORDER_ID: '주문번호',
    SHIPMENT_ID: '출고번호',
    INVENTORY_ID: '재고번호',
    ROUTE_CODE: '공급코스',
    FUND_RULE_ID: '기금규칙번호',
    FUND_HISTORY_ID: '기금이력번호',
    ORDER_DATE: '주문일',
    RECEIVING_DATE: '입고일',
    RETURN_DATE: '반품일',
    SHIPMENT_DATE: '출고일',
    START_DATE: '시작일',
    END_DATE: '종료일',
    QUANTITY: '수량',
    AMOUNT: '금액',
    STATUS: '상태',
    ACTIVE_YN: '사용여부',
    CREATED_AT: '생성일시',
    UPDATED_AT: '수정일시',
  }),
  KEY_NAME: Object.freeze({
    PRODUCER: '생산자번호',
    PRODUCT: '품번',
    AGREEMENT: '약정번호',
    RECEIVING: '입고번호',
    RETURN: '반품번호',
    ORDER: '주문번호',
    SHIPMENT: '출고번호',
    INVENTORY: '재고번호',
    ROUTE: '공급코스',
    FUND_RULE: '기금규칙번호',
    FUND_HISTORY: '기금이력번호',
  }),
  FIELD: Object.freeze({
    MASTER_DATA: Object.freeze({
      ITEM_CODE: '물품코드',
      ITEM_NAME: '물품명',
      PRICE: '금액',
      TEMPERATURE_TYPE: '저장상태',
      STORAGE_PICK_KEY: '저장상태+집품순서',
      PRODUCER_OR_LOGISTICS_SOURCE: '물류지',
      PICKING_ORDER: '집품순서',
      PRODUCER: '생산자',
      COURSE: '코스',
      SUPPLY_TYPE: '공급구분',
      ACTIVE_YN: '사용여부',
    }),
    CHANGELOG: Object.freeze({
      LOG_ID: 'LOG_ID',
      VERSION: '버전',
      CHANGED_AT: '변경일시',
      CHANGE_TYPE: '변경유형',
      MESSAGE: '변경내용',
      RELATED_ID: '관련ID',
      ACTOR: '작업자',
      RESULT: '결과',
    }),
    ANALYTICS: Object.freeze({
      CACHE_ID: 'CACHE_ID',
      METRIC: 'METRIC',
      VALUE: 'VALUE',
      TARGET: 'TARGET',
      CREATED_AT: 'CREATED_AT',
      EXPIRES_AT: 'EXPIRES_AT',
    }),
    API_LOG: Object.freeze({
      API_LOG_ID: 'API_LOG_ID', TIMESTAMP: 'TIMESTAMP', CLIENT: 'CLIENT',
      API_KEY: 'API_KEY', ENDPOINT: 'ENDPOINT', METHOD: 'METHOD',
      STATUS: 'STATUS', RESPONSE_TIME: 'RESPONSE_TIME', USER: 'USER',
      MESSAGE: 'MESSAGE',
    }),
    WEBHOOK: Object.freeze({
      WEBHOOK_ID: 'WEBHOOK_ID', EVENT: 'EVENT', TARGET_URL: 'TARGET_URL',
      METHOD: 'METHOD', STATUS: 'STATUS', LAST_SENT: 'LAST_SENT',
      LAST_RESULT: 'LAST_RESULT',
    }),
    FEATURE_FLAG: Object.freeze({
      FLAG: 'FLAG', DESCRIPTION: 'DESCRIPTION', ENABLED: 'ENABLED',
      TARGET: 'TARGET', UPDATED_AT: 'UPDATED_AT',
    }),
    AUDIT: Object.freeze({
      AUDIT_ID: 'AUDIT_ID',
      TIMESTAMP: 'TIMESTAMP',
      USER: 'USER',
      ROLE: 'ROLE',
      ACTION: 'ACTION',
      ENTITY: 'ENTITY',
      ENTITY_ID: 'ENTITY_ID',
      RESULT: 'RESULT',
      MESSAGE: 'MESSAGE',
      DETAIL: 'DETAIL',
    }),
    NOTIFICATION: Object.freeze({
      NOTIFICATION_ID: 'NOTIFICATION_ID',
      TIMESTAMP: 'TIMESTAMP',
      TYPE: 'TYPE',
      USER: 'USER',
      ENTITY: 'ENTITY',
      ENTITY_ID: 'ENTITY_ID',
      TITLE: 'TITLE',
      MESSAGE: 'MESSAGE',
      STATUS: 'STATUS',
      READ_AT: 'READ_AT',
    }),
    BACKUP: Object.freeze({
      BACKUP_ID: 'BACKUP_ID',
      TIMESTAMP: 'TIMESTAMP',
      USER: 'USER',
      TYPE: 'TYPE',
      TARGET: 'TARGET',
      FILE_NAME: 'FILE_NAME',
      STATUS: 'STATUS',
      MESSAGE: 'MESSAGE',
    }),
    WORKFLOW: Object.freeze({
      WORKFLOW_ID: 'WORKFLOW_ID',
      TIMESTAMP: 'TIMESTAMP',
      ENTITY: 'ENTITY',
      ENTITY_ID: 'ENTITY_ID',
      FROM_STATUS: 'FROM_STATUS',
      TO_STATUS: 'TO_STATUS',
      USER: 'USER',
      ROLE: 'ROLE',
      ACTION: 'ACTION',
      RESULT: 'RESULT',
      MESSAGE: 'MESSAGE',
    }),
    USER: Object.freeze({
      USER_ID: 'USER_ID',
      USER_NAME: 'USER_NAME',
      EMAIL: 'EMAIL',
      ROLE: 'ROLE',
      STATUS: 'STATUS',
      CREATED_AT: 'CREATED_AT',
      UPDATED_AT: 'UPDATED_AT',
    }),
    PROJECT: Object.freeze({
      PROJECT_ID: 'PROJECT_ID',
      PROJECT_NAME: '프로젝트명',
      DESCRIPTION: '설명',
      STATUS: '상태',
      CURRENT_VERSION: '현재버전',
      OWNER: '담당자',
      START_DATE: '시작일',
      PLANNED_END_DATE: '종료예정일',
      CREATED_AT: '생성일시',
      UPDATED_AT: '수정일시',
    }),
    EPIC: Object.freeze({
      EPIC_ID: 'EPIC_ID',
      PROJECT_ID: 'PROJECT_ID',
      EPIC_NAME: 'EPIC명',
      DESCRIPTION: '설명',
      STATUS: '상태',
      PRIORITY: '우선순위',
      OWNER: '담당자',
      START_DATE: '시작일',
      PLANNED_END_DATE: '종료예정일',
      CREATED_AT: '생성일시',
      UPDATED_AT: '수정일시',
    }),
    FEATURE: Object.freeze({
      FEATURE_ID: 'FEATURE_ID',
      EPIC_ID: 'EPIC_ID',
      FEATURE_NAME: 'FEATURE명',
      DESCRIPTION: '설명',
      STATUS: '상태',
      PRIORITY: '우선순위',
      OWNER: '담당자',
      CREATED_AT: '생성일시',
      UPDATED_AT: '수정일시',
    }),
    FUNCTION: Object.freeze({
      FUNCTION_ID: 'FUNCTION_ID',
      FEATURE_ID: 'FEATURE_ID',
      FUNCTION_NAME: '기능명',
      DESCRIPTION: '설명',
      INPUT_DEFINITION: '입력',
      OUTPUT_DEFINITION: '출력',
      RELATED_SHEETS: '관련시트',
      STATUS: '상태',
      OWNER: '담당자',
      CREATED_AT: '생성일시',
      UPDATED_AT: '수정일시',
    }),
    TASK: Object.freeze({
      TASK_ID: 'TASK_ID',
      FUNCTION_ID: 'FUNCTION_ID',
      EPIC_ID: 'EPIC_ID',
      TASK_NAME: '작업명',
      DESCRIPTION: '설명',
      STATUS: '상태',
      PRIORITY: '우선순위',
      OWNER: '담당자',
      START_DATE: '시작일',
      PLANNED_END_DATE: '완료예정일',
      COMPLETED_DATE: '완료일',
      PROGRESS: '진행률',
      CREATED_AT: '생성일시',
      UPDATED_AT: '수정일시',
    }),
  }),
});
